/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        // Obsidian Intelligence Design System
        'surface':                    '#131313',
        'surface-dim':                '#131313',
        'surface-bright':             '#393939',
        'surface-container-lowest':   '#0e0e0e',
        'surface-container-low':      '#1c1b1b',
        'surface-container':          '#201f1f',
        'surface-container-high':     '#2a2a2a',
        'surface-container-highest':  '#353534',
        'on-surface':                 '#e5e2e1',
        'on-surface-variant':         '#c2c6d6',
        'outline':                    '#8c909f',
        'outline-variant':            '#424754',
        'primary':                    '#adc6ff',
        'on-primary':                 '#002e6a',
        'primary-container':          '#4d8eff',
        'secondary':                  '#4edea3',
        'on-secondary':               '#003824',
        'secondary-container':        '#00a572',
        'tertiary':                   '#ffb3ad',
        'tertiary-container':         '#ff5451',
        'error':                      '#ffb4ab',
        'error-container':            '#93000a',
        'background':                 '#131313',
        'on-background':              '#e5e2e1',
        'surface-variant':            '#353534',
        // Semantic
        'bull':   '#4edea3',
        'bear':   '#ff5451',
        'neutral':'#adc6ff',
        'warn':   '#ffd166',
      },
      fontFamily: {
        sans:  ['Inter', 'system-ui', 'sans-serif'],
        mono:  ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-md': ['18px', { lineHeight: '24px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-sm': ['14px', { lineHeight: '20px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-md':     ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-sm':     ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'data-lg':     ['16px', { lineHeight: '24px', fontWeight: '500' }],
        'data-md':     ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'data-sm':     ['11px', { lineHeight: '14px', fontWeight: '400' }],
        'label-xs':    ['10px', { lineHeight: '12px', fontWeight: '500' }],
        'ticker':      ['12px', { lineHeight: '16px', fontWeight: '700' }],
      },
      borderRadius: { DEFAULT: '0px', sm: '0px', md: '0px', lg: '0px' },
      spacing: {
        'gutter': '8px',
        'container-padding': '12px',
      },
      animation: {
        'marquee':    'marquee 35s linear infinite',
        'pulse-slow': 'pulse 3s ease infinite',
        'slide-up':   'slideUp 0.2s ease-out',
        'fade-in':    'fadeIn 0.15s ease-out',
      },
      keyframes: {
        marquee:  { from: { transform: 'translateX(0)' }, to: { transform: 'translateX(-50%)' } },
        slideUp:  { from: { opacity: '0', transform: 'translateY(8px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        fadeIn:   { from: { opacity: '0' }, to: { opacity: '1' } },
      },
    },
  },
  plugins: [],
}
